version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
